### PR TITLE
Fix component css reloading on any change

### PR DESCRIPTION
**Pull request by non25**
This fixes https://github.com/sveltejs/svelte-loader/issues/131 in a weird way. But it works!

### CODE REVIEW

**Comment by non25** [comment]
Webpack 4 relies on `compiler.fileTimestamps` Map to decide if it should reload & rebuild file.
This code inserts virtual file timestamp when virtual file has been created and restores virtual file timestamps after they had been overriden by this code, which doesn't account for virtual files:
https://github.com/webpack/webpack/blob/4a1f068828c2ab47537d8be30d542cd3a1076db4/lib/Watching.js#L147-L156

Maybe there's less hacky way involving inheriting NodeWatchFileSystem and doing that there, but this way is shortest and does the job. Much like having plugin functionality providing virtual files in the loader.

Here's some more context:
https://github.com/sysgears/webpack-virtual-modules/pull/66

**Comment by rogueyoshi** [comment]
Any side-effects?

**Comment by non25** [comment]
I have yet to find them in 4 days of using patched svelte-loader.
Guy who suffered from 40s long rebulds on any change with 20 components using postcss+tailwind+svelte-preprocess tells the same.

It was fixed upstream.
https://github.com/sysgears/webpack-virtual-modules/pull/66#issuecomment-691858805
You can read my detailed explanation below maintainer's response.

Keep in mind that by no means I'm an expert in webpack's internals.

**Comment by trash-and-fire** [comment]
Any updates on this PR? 

It is hard to understand why this loader uses hacky way to inject virtual files into fs. This work is not just for the loader, it needs to be in loader+plugin (as in minicss-extract-plugin). It is much easier to maintain this loader with ability to update VirtualModulesPlugin using package.json instead of copy/paste some parts of plugin in svelte-loader code directly.

**Comment by larixer** [comment]
@Smittyvb I would be open to pull request on `webpack-virtual-modules` side to export some interface that allow it to be usable inside the svelte loader. Probably the source code in `webpack-virtual-modules` should be converted into TypeScript as well (this is a separate concern). I really didn't expect that this webpack plugin will be used by more than a couple dozens of people. But since it is being used, lets make it usable in more scenarios, if you are open to it.

**Comment by Smittyvb** [comment]
This is now superseded by #146.

**Pull request closed without merging**
