### PR TITLE
make onwarn option work

### PR DESCRIPTION
**Pull request by russelgal**

### CODE REVIEW

**Comment by Conduitry** [comment]
Sorry, I didn't see this PR when I made #105! This was fixed in 2.13.5.

**Comment by JohnnyFun** [comment]
Looks like webpack options ignore `function` options, so if I pass an `onwarn` function, it doesn't seem to come through. 

I'm working around by just using a fork of this project for now like:

```
const options = Object.assign({}, getOptions(this))

// `getOptions` doesn't support functions...
// https://github.com/webpack/loader-utils/blob/v2.0.0/lib/getOptions.js
options.onwarn = (warning, handle) => {
	if (warning.code === 'a11y-label-has-associated-control') return // we have many labels without `for` attr--can put inputs inside label
	handle(warning)
}
```

**Comment by JohnnyFun** [comment]
Perhaps an array of strings of warning codes to ignore instead? (assuming I'm not missing something)

**Comment by JohnnyFun** [comment]
Just discovered webpack's `ignoreWarnings` option, fwiw. So you could delete the `onWarn` function and add a bit to the docs like `ignoreWarnings: [/A11y: A form label must be associated with a control/]` as an example.

https://webpack.js.org/configuration/#

**Pull request closed without merging**
