### PR TITLE
Publish only necessary files to NPM

### PR DESCRIPTION
**Pull request by Artefall**
NPM package must include only necessary files. This package includes ```tests```, ```examples``` and other files, that have no sense for NPM package.

### CODE REVIEW

**Comment by kaisermann** [comment]
A `.npmignore` file would probably be more flexible and wouldn't need to edit the package.json

**Comment by Conduitry** [comment]
In general I think explicit whitelists of files to include in the package are preferable to blacklists.

**Comment by lukeed** [comment]
Yeah, specifying the desired files is much more explicit, common, and I'm pretty sure its the npm recommendation

**Comment by kaisermann** [comment]
Ook, I was convinced. Definetely more explicit and easier to grasp 👌

**Comment by lukeed** [comment]
Thanks!

**Pull request merged**
